name: Run Playwright Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
      tags:
        description: 'Select the test tags'
        required: true

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright
        run: npx playwright install

      - name: Run Playwright Tests
        env:
          TEST_ENV: ${{ github.event.inputs.environment }}
        run: test_env=${{ github.event.inputs.environment }} npx playwright test --grep ${{ github.event.inputs.tags }}
