name: Run Playwright Tests

on:
  repository_dispatch:
    types: [run-tests]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        env:
          TEST_ENV: ${{ github.event.client_payload.env }}
        run: test_env=${{ github.event.client_payload.env }} npx playwright test --grep ${{ github.event.client_payload.grep }}
